version: '3.4'
services:
  local:
    build: .
    image: net-bet
    container_name: net-bet-local
    entrypoint: lein
    volumes:
      - .:/usr/net-bet-backend
  interactive:
    build: .
    image: net-bet
    container_name: net-bet-interactive
    entrypoint: bash
    volumes:
      - .:/usr/net-bet-backend